UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Nunc at leo sed augue bibendum suscipit. ' WHERE (`report_id` = '1');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Aliquam dapibus orci et lorem mollis laoreet.' WHERE (`report_id` = '2');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Sed pellentesque mauris nec rhoncus aliquet.' WHERE (`report_id` = '4');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'In ultricies facilisis imperdiet.' WHERE (`report_id` = '5');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Cras ut faucibus nibh, sit amet congue odio.' WHERE (`report_id` = '6');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Aenean hendrerit iaculis dolor, vel porttitor justo dictum et.' WHERE (`report_id` = '7');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Vestibulum semper lectus at ligula sodales luctus' WHERE (`report_id` = '8');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Vestibulum semper lectus at ligula sodales luctus.\n\nVestibulum semper lectus at ligula s' WHERE (`report_id` = '9');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Phasellus varius ex eu elit pretium placerat.' WHERE (`report_id` = '10');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Fusce sagittis luctus ex eget luctus.' WHERE (`report_id` = '12');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Maecenas rhoncus a dolor in volutpat.' WHERE (`report_id` = '13');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Donec sit amet augue non tellus pretium vestibulum.' WHERE (`report_id` = '14');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Donec sit amet augue non tellus pretium vestibulum.' WHERE (`report_id` = '15');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Donec ornare eleifend tellus, vel tempor dolor ullamcorper eu.' WHERE (`report_id` = '16');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'Nulla lobortis quam sit amet quam lobortis justo lectus' WHERE (`report_id` = '17');
UPDATE `agentdiscoveries`.`location_reports` SET `report_body` = 'in imperdiet purus sollicitudin. Phasellus vel diam dui.' WHERE (`report_id` = '18');
